FAD-5695 fixed library to work with ioredis client
SparkPost/node-redis-timeseries pull request #1
Opened 2017-12-18 22:16 UTC by gwalls

2017-12-20 21:55 UTC, beardyman commented on package.json
>    "version": "0.4.0",
make 1.0.0

2018-01-05 15:18 UTC, beardyman requested changes
What about tests?  We should update/add to whatever tests are in place and probably set this up in CI to have them auto run.

2018-01-05 15:18 UTC, beardyman commented on src/timeseries.js
> +      if (result instanceof Array) {
I would comment here explaining that different clients libs return different things ... just explain why you're doing what you're doing.

2018-01-09 16:44 UTC, gwalls commented
@beardyman there are currently no tests and no CI. I can set these up if you think it's worth the time right now?

2018-01-09 17:53 UTC, beardyman commented
@gwalls Theres a tests folder with a simple test in it.  I guess we should probably wait and defer tests since it could be a decent undertaking to write tests for this stuff.  I'm going to ping a few peeps about it and see how they feel.

2018-01-09 21:22 UTC, beardyman commented
deferring tests from convo irl

2018-01-09 21:22 UTC, beardyman approved these changes

2018-01-09 23:05 UTC, merged